version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
  backend:
    build: ./backend
    ports:
      - "1337:1337"
    volumes:
      - ./backend/backend:/app
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: password
      DATABASE_PORT: 3306
  # db:
  #   image: mysql:5.7
  #   platform: linux/amd64
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: strapi
  #     MYSQL_USER: strapi
  #     MYSQL_PASSWORD: password
  #   ports:
  #     - "3306:3306"
